# Exercises

These exercises are a mix of Python and pandas/EDA practice. Most should be no more than a few lines of code! 

In [3]:
# here is a Python list:

a = [1, 2, 3, 4, 5, 6]

# get a list containing the last 3 elements of a
tempList = []
tempList.append(a[-1])
tempList.append(a[-2])
tempList.append(a[-3])
print(tempList)

# reverse the list
tempList.reverse()
print(tempList)
# get a list where each entry in a is squared (so the new list is [1, 4, 9, 16, 25, 36])
tempList2 = []
for i in a:
    tempList2.append(i**2)
print(tempList2)


[6, 5, 4]
[4, 5, 6]
[1, 4, 9, 16, 25, 36]


In [11]:
import numpy as np
# create a numpy array from this list
b = [1, 2, 3, 4, 5, 6] # change this
b = np.array(b)

In [12]:
# find the mean of b
print(np.mean(b))

3.5


In [13]:
# get a list where each entry in b is squared (so the new numpy array is [1, 4, 9, 16, 25, 36])
# use a different (numpy-specific) approach
tempList3 = []
for i in b:
    tempList3.append(i**2)
tempList3 = np.array(tempList3)
print(tempList3)

[ 1  4  9 16 25 36]


In [15]:
# change b from a length-6 list to a 2x3 matrix
tempList4 = np.asmatrix([[1, 4, 9], [16, 25, 36]])

In [16]:
# find the mean value of each row
rowMean = tempList4.mean(axis=1)
print(rowMean)

[[ 4.66666667]
 [25.66666667]]


In [18]:
# find the mean value of each column
columnMean = tempList4.mean(axis=0)
print(columnMean)

[[ 8.5 14.5 22.5]]


In [19]:
# find the third column of b
print(tempList4[:,2])

[[ 9]
 [36]]


In [ ]:
# load in the "starbucks_clean.csv" dataset
import pandas as pd
df = pd.read_csv('../data/starbucks_clean.csv')

In [ ]:
# this is nutritional info for starbucks items
# let's see if we can answer some questions

# what is the average # calories across all items?
print(df["Calories"].mean())

In [ ]:
# how many different categories of beverages are there?
categories = df["Beverage_category"].value_counts()

In [ ]:
# what is the average # calories for each beverage category?
df.groupby(["Beverage_category"])["Calories"].mean()

In [ ]:
# what beverage preparation includes the most sugar on average?
max(df.groupby(["Beverage_category"])["Sugar"].mean())

In [ ]:
# what is the average % daily value calcium content for each beverage?
df.groupby(["Beverage_category"])(["Calcium"]).mean()

In [ ]:
# It's bulking season. What drink should Naitian get so that he maximizes protein but minimizes calories?
# (you can use more than one line for this one)
# there are multiple valid approaches you can take for this (with different answers)
# I know that you want more calories for bulking season but whatever this is MDST, not Michigan Muscle Club okay
max(df[["Calories", "Protein"]].agg({"Calories": "min", "Protein": "max"}))

In [20]:
# plot the distribution of the number of calories in drinks using matplotlib
import matplotlib as plt
df["Calories"].plot(kind='scatter', x='x', y='y')

In [21]:
# plot the same distribution using seaborn. what about a density plot instead?
import seaborn
seaborn.scatterplot(x='x', y='y', data=df["Calories"])
seaborn.distplot(df["Calories"], hist=True, kde=True)

In [ ]:
# plot calories against total fat using seaborn
df["Calories"].scatterplot(by=df["Fat"])

In [ ]:
# plot the distribution of calories in Short, Tall, Grande, and Venti drinks
# (you can use multiple lines for this)
# twist: you should also include the Nonfat Milk drinks that also have an associated size.

# you can decide how you want to visualize this. Colors? Small multiples? Density vs histogram?
# the starbucks is your oyster.
